insert into ubicaciones (nombre_ubicacion) values
('Arica'),
('Iquique'),
('Antofagasta'),
('Copiapó'),
('La Serena'),
('Coquimbo'),
('Valparaíso'),
('Viña del Mar'),
('Santiago'),
('Rancagua'),
('Talca'),
('Chillán'),
('Concepción'),
('Los Ángeles'),
('Temuco'),
('Valdivia'),
('Osorno'),
('Puerto Montt'),
('Coyhaique'),
('Punta Arenas');